using Brainiac.HTN.Nodes;
using Brainiac.Design.Attributes;
using Uprising.Enums;

namespace Uprising.Nodes.PrimitiveTasks
{
	public class FollowPath : PrimitiveTask
	{
		public FollowPath() : base("Follow Path", "The AI will follow a given path which needs tobe generated by a Find Path precondition first.")
		{
		}

		protected PathID _path;

		[DesignerEnum("Path", "The id of the path we want to follow.", "CategoryBasic", DesignerProperty.DisplayMode.List, 0, DesignerProperty.DesignerFlags.NoFlags, null)]
		public PathID Path
		{
			get { return _path; }
			set { _path= value; }
		}
	}
}
