//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainiac.HTN.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Brainiac.HTN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods.
        /// </summary>
        public static string BehaviorGroupName {
            get {
                return ResourceManager.GetString("BehaviorGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string CategoryBasic {
            get {
                return ResourceManager.GetString("CategoryBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string MethodPriority {
            get {
                return ResourceManager.GetString("MethodPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The priority used when listing the found methods. Methods with a highr priority will be processed first..
        /// </summary>
        public static string MethodPriorityDesc {
            get {
                return ResourceManager.GetString("MethodPriorityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Type.
        /// </summary>
        public static string MethodType {
            get {
                return ResourceManager.GetString("MethodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the method..
        /// </summary>
        public static string MethodTypeDesc {
            get {
                return ResourceManager.GetString("MethodTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Method.
        /// </summary>
        public static string NewBehavior {
            get {
                return ResourceManager.GetString("NewBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound Tasks.
        /// </summary>
        public static string NodeGroupCompoundTasks {
            get {
                return ResourceManager.GetString("NodeGroupCompoundTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods.
        /// </summary>
        public static string NodeGroupMethods {
            get {
                return ResourceManager.GetString("NodeGroupMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators.
        /// </summary>
        public static string NodeGroupOperators {
            get {
                return ResourceManager.GetString("NodeGroupOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overrides.
        /// </summary>
        public static string NodeGroupOverrides {
            get {
                return ResourceManager.GetString("NodeGroupOverrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preconditions.
        /// </summary>
        public static string NodeGroupPreconditions {
            get {
                return ResourceManager.GetString("NodeGroupPreconditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primitive Tasks.
        /// </summary>
        public static string NodeGroupPrimitiveTasks {
            get {
                return ResourceManager.GetString("NodeGroupPrimitiveTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string OperatorAnd {
            get {
                return ResourceManager.GetString("OperatorAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks all preconditions attached as long as they are true. Fails if any is false..
        /// </summary>
        public static string OperatorAndDesc {
            get {
                return ResourceManager.GetString("OperatorAndDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string OperatorAny {
            get {
                return ResourceManager.GetString("OperatorAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tries all attached tasks and uses the first one that can be added to the plan..
        /// </summary>
        public static string OperatorAnyDesc {
            get {
                return ResourceManager.GetString("OperatorAnyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If.
        /// </summary>
        public static string OperatorIf {
            get {
                return ResourceManager.GetString("OperatorIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeds when all the preconditions are true as well as the tasks..
        /// </summary>
        public static string OperatorIfDesc {
            get {
                return ResourceManager.GetString("OperatorIfDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string OperatorOr {
            get {
                return ResourceManager.GetString("OperatorOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks all preconditions attached until one is true. Fails if none is true..
        /// </summary>
        public static string OperatorOrDesc {
            get {
                return ResourceManager.GetString("OperatorOrDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negate.
        /// </summary>
        public static string PreconditionNegate {
            get {
                return ResourceManager.GetString("PreconditionNegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negates the precondition..
        /// </summary>
        public static string PreconditionNegateDesc {
            get {
                return ResourceManager.GetString("PreconditionNegateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prio.
        /// </summary>
        public static string UnitsPriority {
            get {
                return ResourceManager.GetString("UnitsPriority", resourceCulture);
            }
        }
    }
}
